### ISSUE TITLE
General TODO list

### ISSUE THREAD

**Issue by Borales** [Simplyii/archived_core#1]
Structure
-------------
- [ ] Namespaces?
- [ ] Modify autoloader
- [ ] Basic guidelines on wiki
- [ ] Interfaces

Search engines
---------------------
- [ ] Lucene [yii wiki](http://www.yiiframework.com/wiki/248/adding-search-to-yii-blog-example-using-zend-lucene)
- [ ] Sphinx [mitallast/yii-sphinx](https://github.com/mitallast/yii-sphinx), [maxlapko/rt_sphinx_behavior](https://github.com/maxlapko/rt_sphinx_behavior) and [zoer/yii-sphinx](https://github.com/zoer/yii-sphinx)
- [ ] Solr [highload.com.ua](http://highload.com.ua/index.php/2010/01/13/solr-%D0%BF%D0%BE%D0%BB%D0%BD%D0%BE%D1%82%D0%B5%D0%BA%D1%81%D1%82%D0%BE%D0%B2%D1%8B%D0%B9-%D0%BF%D0%BE%D0%B8%D1%81%D0%BA-%D0%BE%D1%82-apache-%D0%BD%D0%B0-%D0%BE%D1%81%D0%BD%D0%BE%D0%B2%D0%B5-lucene/)

API
-----
- [ ] Mail delivery ( [PostMark](https://postmarkapp.com/) )

DB
----
- [ ] MySQL, Postgre
- [ ] NoSQL [MongoYii](https://github.com/Sammaye/MongoYii) [YiiMongoDbSuite](https://github.com/canni/YiiMongoDbSuite)

Testing
----------
- [ ] Implement UI-testing using Travis-CI [see http://about.travis-ci.org/docs/user/gui-and-headless-browsers/#Using-xvfb-to-Run-Tests-That-Require-GUI-(e.g.-a-Web-browser)]
- [ ] Try [Codeception](https://github.com/Codeception/Codeception/blob/master/docs/modules/Yii1.md)
